# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Map
  description: Map section
  icon: location_searching
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  latitude: 18.003339767456055
  longitude: 79.55231475830078
  name: "STPI Incubation Center, Kakatiya IT Park, Hanamkonda, Telangana 506001"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  name: Yayin AI Lab

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
